<template>
  <article class="max-w-4xl mx-auto px-4 py-12">
    <div class="prose prose-lg max-w-none">
      <div class="mb-8 pb-6 border-b border-gray-200">
        <p class="text-sm text-gray-600 italic mb-4">
          Disclaimer: The opinions expressed herein are my own personal opinions and do not represent my employer's view in any way.
        </p>
      </div>

      <h1 class="text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
      
      <p class="text-sm text-gray-500 mb-8">
        Effective date: November 4, 2025
      </p>

      <p class="text-gray-700 leading-relaxed mb-6">
        This blog ("us", "we", or "our") operates this website (the "Service").
      </p>

      <p class="text-gray-700 leading-relaxed mb-6">
        This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
      </p>

      <p class="text-gray-700 leading-relaxed mb-8">
        We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Definitions</h2>

      <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-3">Service</h3>
      <p class="text-gray-700 leading-relaxed mb-4">
        Service is this website and blog operated as a personal project.
      </p>

      <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-3">Personal Data</h3>
      <p class="text-gray-700 leading-relaxed mb-4">
        Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
      </p>

      <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-3">Usage Data</h3>
      <p class="text-gray-700 leading-relaxed mb-4">
        Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
      </p>

      <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-3">Cookies</h3>
      <p class="text-gray-700 leading-relaxed mb-4">
        Cookies are small pieces of data stored on your device (computer or mobile device).
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Information Collection and Use</h2>
      
      <p class="text-gray-700 leading-relaxed mb-6">
        We collect several different types of information for various purposes to provide and improve our Service to you.
      </p>

      <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-3">Types of Data Collected</h3>

      <h4 class="text-lg font-semibold text-gray-800 mt-5 mb-2">Personal Data</h4>
      <p class="text-gray-700 leading-relaxed mb-4">
        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
      </p>
      <ul class="list-disc list-inside space-y-2 mb-6 text-gray-700">
        <li>Email address</li>
        <li>First name and last name (optional, for newsletter)</li>
        <li>Cookies and Usage Data</li>
      </ul>

      <h4 class="text-lg font-semibold text-gray-800 mt-5 mb-2">Usage Data</h4>
      <p class="text-gray-700 leading-relaxed mb-4">
        We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </p>

      <h4 class="text-lg font-semibold text-gray-800 mt-5 mb-2">Tracking & Cookies Data</h4>
      <p class="text-gray-700 leading-relaxed mb-4">
        We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Use of Data</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        We use the collected data for various purposes:
      </p>
      <ul class="list-disc list-inside space-y-2 mb-6 text-gray-700">
        <li>To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To allow you to participate in interactive features (such as comments and newsletter)</li>
        <li>To provide support when needed</li>
        <li>To gather analysis or valuable information so that we can improve our Service</li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent and address technical issues</li>
      </ul>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Newsletter</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        If you subscribe to our newsletter, we will use your email address (and optionally your name) solely to send you blog updates and articles. We will never:
      </p>
      <ul class="list-disc list-inside space-y-2 mb-6 text-gray-700">
        <li>Sell your email address to third parties</li>
        <li>Use your email for marketing purposes</li>
        <li>Share your information with anyone else</li>
        <li>Send you spam or excessive emails</li>
      </ul>
      <p class="text-gray-700 leading-relaxed mb-4">
        You can unsubscribe at any time using the link provided in every newsletter email.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Comments via Giscus</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        Our blog uses Giscus for comments, which is powered by GitHub Discussions. When you post a comment, you are using GitHub's services and are subject to GitHub's Privacy Policy. We do not store or control comment data - it is managed entirely by GitHub.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Analytics</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        We may use third-party Service Providers to monitor and analyze the use of our Service.
      </p>

      <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-3">Google Analytics</h3>
      <p class="text-gray-700 leading-relaxed mb-4">
        Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services.
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on.
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" class="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy?hl=en</a>
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Data Retention</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        Newsletter subscription data is retained until you unsubscribe. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Security of Data</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Your Data Protection Rights (GDPR)</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        If you are a resident of the European Economic Area (EEA), you have certain data protection rights:
      </p>
      <ul class="list-disc list-inside space-y-2 mb-6 text-gray-700">
        <li><strong>The right to access:</strong> You have the right to request copies of your personal data.</li>
        <li><strong>The right to rectification:</strong> You have the right to request that we correct any information you believe is inaccurate or incomplete.</li>
        <li><strong>The right to erasure:</strong> You have the right to request that we erase your personal data, under certain conditions.</li>
        <li><strong>The right to restrict processing:</strong> You have the right to request that we restrict the processing of your personal data, under certain conditions.</li>
        <li><strong>The right to object to processing:</strong> You have the right to object to our processing of your personal data, under certain conditions.</li>
        <li><strong>The right to data portability:</strong> You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
      </ul>
      <p class="text-gray-700 leading-relaxed mb-4">
        If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Links to Other Sites</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Children's Privacy</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        Our Service does not address anyone under the age of 13 ("Children").
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Changes to This Privacy Policy</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "effective date" at the top.
      </p>
      <p class="text-gray-700 leading-relaxed mb-4">
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
      </p>

      <h2 class="text-2xl font-semibold text-gray-900 mt-10 mb-4">Contact</h2>
      
      <p class="text-gray-700 leading-relaxed mb-4">
        If you have any questions about this Privacy Policy, please feel free to reach out via the contact information on the home page or through social media.
      </p>

      <div class="mt-12 pt-8 border-t border-gray-200">
        <router-link 
          to="/"
          class="inline-flex items-center text-blue-600 hover:text-blue-700 hover:underline"
        >
          <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
          </svg>
          Back to Home
        </router-link>
      </div>
    </div>
  </article>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useSeo, type SeoMetaTags } from '../composables/useSeo'

const seoTags = ref<SeoMetaTags | null>(null)

onMounted(() => {
  seoTags.value = {
    title: 'Privacy Policy',
    description: 'Privacy policy for this blog. Learn about how we collect, use, and protect your personal data.',
    type: 'website',
    url: window.location.href
  }
})

useSeo(seoTags)
</script>

<style scoped>
/* Styles are handled by Tailwind classes in template */
</style>
